# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b40d12b83e302e0cec3a7ba5b5af19aaf55c983b41f3f52ede7e5837af5cc368e16d0846f7b031bead80ea07330a0119069c87b099ed3abae878876c722e52

test:
  secret_key_base: f7144c6a559fa4abbac768a7dfd6452f5ee339ab0621fdb5ec81cc98e4d486a9f2f3a5b886bd230d2586c98929c6cd4a85709097e893f5aba0a48a23e8ccd452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
